name: Build and Publish DEB Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev debhelper

    - name: Fix permissions
      run: chmod 755 debian/DEBIAN/postinst

    - name: Build DEB package
      run: dpkg-deb --build debian portip.deb

    - name: Create repository structure
      run: |
        mkdir -p repo/deb
        mv portip.deb repo/deb/
        cd repo/deb
        dpkg-scanpackages . /dev/null > Package
        gzip -9c Package > Packages.gz

    - name: Commit and push
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add repo/deb/Package repo/deb/Packages.gz
        git commit -m 'Update Package files'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload DEB package and metadata
      uses: actions/upload-artifact@v2
      with:
        name: portip-repo
        path: repo/deb
